### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by zandbelt** [solid/oidc-rp#18]
Why would you want to do this as part of Solid? Why not rely on an existing [certified](https://openid.net/developers/certified/) OIDC Node library/client e.g. https://github.com/panva/node-openid-client  and spend resources to develop/maintain this code on the core project instead?

**Comment by dmitrizagidulin** [comment]
@zandbelt - always a good question! Don’t worry, the Solid devs are always careful to do prior art research and use available components whenever possible.

At the time when we were implementing Webid-OIDC, there were no other libraries that worked both on the server (in Node.js) and in the browser (using the Web Crypto API). (Plus we were under a requirement to also use and embeddable OP library in the server.)

This RP library could be OIDC certified, we just never got around to it.

Since that time, at least one other library has been developed that might meet our criteria. We’re actually currently investigating which of those libs we can just use, so that we can maintain the least number of libs possible just like you said.

**Comment by dmitrizagidulin** [comment]
Closing this issue. (https://github.com/panva/node-openid-client is for Node only, not for browsers.)
